#include "ObstacleChooser.hpp"

#include "obstacles/ClimbWall.hpp"
#include "obstacles/Crusher.hpp"
#include "obstacles/DeathZone.hpp"
#include "obstacles/Door.hpp"
#include "obstacles/HeightHole.hpp"
#include "obstacles/Hole.hpp"
#include "obstacles/Laser.hpp"
#include "obstacles/MetalGate.hpp"
#include "obstacles/MetalGateDoor.hpp"
#include "obstacles/MovingPlatform.hpp"
#include "obstacles/MovingSidewalk.hpp"
#include "obstacles/SlideObstacle.hpp"
#include "obstacles/Trap.hpp"
#include "obstacles/Turret.hpp"
#include "obstacles/WallJumpZone.hpp"
#include "obstacles/WidthHole.hpp"
